version: "3"
services:
  apigateway:
    image: apigateway:v1
    container_name: apigateway
    ports:
      - 8081:8081
  atendees:
    image: atendees:v1
    container_name: "atendees"
    ports:
      - 8082:8082
    depends_on:
      - apigateway
  matches:
    image: matches:v1
    container_name: "matches"
    ports:
      - 8083:8083
    depends_on:
      - apigateway
  orders:
    image: orders:v1
    container_name: "orders"
    ports:
      - 8084:8084
    depends_on:
      - apigateway
  payments:
    image: payments:v1
    container_name: "payments"
    ports:
      - 8085:8085
    depends_on:
      - apigateway